#!/bin/bash

# Script that sets environment variables required to run custom Arbor installation

# check if PATH exists and set environment variable accordingly
if [[ ! -v PATH ]]; then
	export PATH=$(readlink -f ~/arbor/bin)
else
	export PATH=$(readlink -f ~/arbor/bin):$PATH
fi

# check if LD_LIBRARY_PATH exists and set environment variable accordingly
if [[ ! -v LD_LIBRARY_PATH ]]; then
	export LD_LIBRARY_PATH=$(readlink -f ~/arbor/lib)
else
	export LD_LIBRARY_PATH=$(readlink -f ~/arbor/lib):$LD_LIBRARY_PATH
fi

# check if PYTHONPATH exists and set environment variable accordingly
if [[ ! -v PYTHONPATH ]]; then
	export PYTHONPATH=$(readlink -f ~/arbor/lib/python3.8/site-packages) # or: .../python3.6/..., etc.
else
	export PYTHONPATH=$(readlink -f ~/arbor/lib/python3.8/site-packages):$PYTHONPATH # or: .../python3.6/..., etc.
fi

# set CMAKE_PREFIX_PATH environment variable
export CMAKE_PREFIX_PATH=$(readlink -f ~/arbor)
